name: dizzbase_client
description: Flutter client for the dizzbase node.js realtime database backend.
version: 0.0.15
homepage: https://dizzweb.com
repository: https://github.com/dizzweb-GmbH/dizzbase_client_flutter

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  socket_io_client: ^2.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
